### PR TITLE
Update atari.py

### PR DESCRIPTION
**Pull request by k4ntz**
Added the "return" to the render method, otherwise it's not possible to get the rgb array (to upsumple or register video)

### CODE REVIEW

**Comment by davide-tateo90** [comment]
We are not so sure that this is the correct way to implement this functionality.
The render function interface doesn't support returning a value.
However, we understand the necessity of recording atari RGB images, and we are considering how to expose this functionality properly.

We need to discuss this issue, and then we will consider this pull request, or close it if we have a better solution.

**Comment by VanillaWhey** [comment]
One could also just include the original observations, which are the same as the rendered image, in the info in the ``step`` method. The memory has been used anyway.

**Comment by davide-tateo90** [comment]
No, the observation should be a history of grayscale images. @k4ntz needs RGB images to save a video.
However, we are not sure that returning the image in the render is a good idea. I would rather prefer to have a separate method and an ad-hoc function in the core.

**Comment by davide-tateo90** [comment]
I'll close this pull request, as I've updated the TODO for MushroomRL 2.0, in which we plan to implement a proper record method for environments.

**Pull request closed without merging**
